[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto
addopts = -v --cov=. --cov-report=xml:code_coverage/coverage.xml --cov-report=html:code_coverage/htmlcov --cov-report=term-missing
